### ISSUE TITLE
TODO list for some useful improvements

### ISSUE THREAD

**Issue by bfairkun** [bfairkun/GenometracksByGenotype#1]
- [x] Allow tab delimited list of input files
- [x] Allow groups for different phenotypes
- [x] Allow averaging by group rather than genotype, or group and genotype
- [x] Mark files as normal or inverted for minus strand bigwigs
